### ISSUE TITLE
How to represent Entity in Edge API?

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql-artemis-extension#14]
The Currently model

```java
/**
 * @param <IN>  the inbound Entity
 * @param <OUT> the outbound entity
 */
public interface EdgeEntity<OUT, IN> {

    /**
     * Gets the inbound entity
     *
     * @return the inbound entity
     */
    IN getInbound();

    /**
     * Gets the outbound entity
     *
     * @return the outbound entity
     */
    OUT getOutbound();
}
```

However, this current version does not support very well when there are more than one Edge types, e.g.: give this code:

```java

        Person ada =...; 
        Technology java = ...;
        Technology cloud = ...;

       graph.edge(ada, "lives" "Sao Paulo");
       graph.edge(ada, "works", cloud);
       graph.edge(ada, "works", java);

```
![01](https://user-images.githubusercontent.com/863011/34843606-0f38ac30-f6f6-11e7-8661-10e8bfcdb269.png)

```java
EdgeEntity<Person,?> edges = graph.getTraversalEdge();
//that gonna return both: cities and technology edge

```

That makes me not full confidence in this current API.

## The Options that I have in my mind:

what I thought: 

###  2) Changes to add generics in the methods with throw class cast exception:

```java
public interface EdgeEntity {

T <T> getInbound();

T <T> getOutbound();
}
```

###  3)  Make the methods to return Object:

```java
public interface EdgeEntity {

Object getInbound();

Object getOutbound();
}

```

###  4) another suggestion

To know more about Graph API: https://dzone.com/articles/have-a-fun-moment-with-graph-and-java

**Comment by otaviojava** [comment]
I like the Option 2

**Comment by jesse-gallagher** [comment]
Unless there ends up being another clever way around it, I like option 2 as well, mostly on the basis that the logical thing to do after fetching is to do a class cast anyway, and users could pick Object themselves if they can't be sure at the time.

**Comment by otaviojava** [comment]
Nice, I also shared it in the tinkerpop email list:
https://groups.google.com/forum/#!topic/gremlin-users/QO8paXoqJ7A

**Comment by furlaneto** [comment]
I prefer option 2 too because if we want the object we can get after like @jesse-gallagher said

**Comment by otaviojava** [comment]
So, let's keep the option 2.
