### ISSUE TITLE
Enable use of remote graph

### ISSUE THREAD

**Issue by bsorrentino** [eclipse/jnosql-artemis-extension#27]
Currently i'm using the [DSE Graph](https://www.datastax.com/products/datastax-enterprise-graph) with remote connection 

In this context I haven't available **Graph** object but only **GraphTraversalSource** so it is impossible for me to call **addVertex()** and more in general I've difficult to perform create/update operations

I've forked this project trying to solve this problem ... are you interested in such implementation ? Is it compliant with your strategy ?

**Comment by otaviojava** [comment]
Hey @bsorrentino 
Yes, that looks good.
Thank you

**Comment by bsorrentino** [comment]
I'm glad to read this

Currently I've almost complete implementation (just removing Graph object usage)  but have some problems with Unit Tests because is the first time that I face with Junit5, CDI and Mokito together.  

Concerning unit test for graph I used Tinkerpop in memory graph representation with classical testing approach. Hope I solve this problems shortly

**Comment by otaviojava** [comment]
Nice, @bsorrentino , please, open a PR, so I can help you.

**Comment by otaviojava** [comment]
Hey, @bsorrentino  I merged the code, could you test?

Please, set the version **0.0.6-SNAPSHOT** as a dependency.
```xml
  <dependency>
            <groupId>org.jnosql.artemis</groupId>
            <artifactId>graph-extension</artifactId>
            <version>0.0.6-SNAPSHOT</version>
        </dependency>
```
Defines the sonotype snapshots repository in your pom.xml

```xml
   <repositories>
        <repository>
            <id>sonatype.snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

Makes a GraphTraversalSourceSupplier available to CDI.

```java

    @Produces
    @ApplicationScoped
    public GraphTraversalSourceSupplier getSupplier() {
        return () -> graph.traversal();
    }
```

Done, that is ready to use:


```java
    @Inject
    @GraphTraversalSourceOperation
    private GraphTemplate template;

```


The sample code is here:

- https://github.com/JNOSQL/artemis-demo/tree/master/artemis-demo-java-se/graph-neo4j
- https://github.com/JNOSQL/artemis-demo/blob/master/artemis-demo-java-se/graph-neo4j/src/main/java/org/jnosql/artemis/demo/se/graph/BookTraveresalApp.java

**Comment by bsorrentino** [comment]
Hi @otaviojava 

Sorry for late in answer but lately I've been keept busy on others topics, out of Graph space

I'll back soon on your great implementation because I need that.

Q: 
> Graph implementation is not in extension anymore. Is it moved in main artemis project ?

**Comment by otaviojava** [comment]
Thank you :)
