### ISSUE TITLE
Why is this not archived?

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql-artemis-extension#41]
The https://github.com/eclipse/jnosql-artemis repository is archived, so wonder, why this extension repository isn't?

**Comment by otaviojava** [comment]
This one is extensions and not the mapper implementation itself.

**Comment by keilw** [comment]
So where do dependencies under `org.jnosql.artemis`, especially `artemis-parent` now reside, as these artifects are now in the archived repo?

**Comment by otaviojava** [comment]
No, yet.

**Comment by keilw** [comment]
Ok we'll have to handle it. Where do you generally see the diana-drivers and this repo, at eclipse (this oga), eclipse-ee4j or a different location, e.g. the original jnosql orga?
IMO the main jnosql project should be under eclipse-ee4j, take all the other Jakarta EE projects like https://github.com/eclipse-ee4j/jsonb-api and https://github.com/eclipse-ee4j/yasson for example.

**Comment by otaviojava** [comment]
I don't know.
That is a @waynebeaton decision.

**Comment by keilw** [comment]
It may also be for the Spec Committee, but we have a lot of work for Jakarta EE 8, so I'll wait a bit before raising it there. It does not prevent the refactoring towards org.eclipse.

**Comment by waynebeaton** [comment]
Some time after the Jakarta EE 8 release, the Specification Committee will likely compel the creation of a new "Jakarta EE" top level project as a home for related specification projects. When the dust settles on that, we can decide whether or not it makes sense to move Eclipse JNoSQL.

**Comment by keilw** [comment]
The new Jakarta EE top level project is already there: https://github.com/eclipse-ee4j/nosql so only the relevant parts of the "compatible implementation" would have to move wherever all those Jakarta EE implementations are supposed to go. Whether this is an implementation or an extension, that is a separate question.

**Comment by waynebeaton** [comment]
> The new Jakarta EE top level project is already there: https://github.com/eclipse-ee4j/nosql so only the relevant parts of the "compatible implementation" would have to move wherever all those Jakarta EE implementations are supposed to go. 

No.

Under the Eclipse Development Process, a Top-Level Project is an organizational unit that defines an overall mission and scope for a collection of Projects. Eclipse EE4J is a top-level project. Eclipse Technology is a top-level project. 

Jakarta NoSQL is a Specification Project that currently operates under the EE4J Top-level project. Eclipse JNoSQL implements (will implement?) the specification defined by the Jakarta NoSQL Specification project. These are two separate projects. There is *no specific need* for them to have any direct project relationship. In fact, it's better that they be kept separate.

**Comment by keilw** [comment]
So is it a coincidence, the other implementing projects like Eclipse Yasson, EclipseLink, etc. are all under EE4J and does it mean, the JNoSQL project could also stay under the "Technology" umbrella for some time?
JNoSQL already implements a Snapshot version of Jakarta NoSQL, see https://github.com/eclipse/jnosql/blob/master/diana/diana-core/pom.xml and other POMs.

I guess it's also a question, if separate repositories for the spec project and implementation are preferred, or one for everything (like jsonp)?

**Comment by waynebeaton** [comment]
At some point somebody thought that having Eclipse Yasson and EclipseLink under EE4J was a good idea. It makes sense to have these projects under the guidance of the same PMC that oversees Eclipse Glassfish, but there's no requirement that this relationship exist. You've probably noticed that Eclipse Jetty (which I believe is a Compatible Implementation of Jakarta Servlets) is under the Eclipse RT Top-level project and there is (AFAIK) no plans to move it.

> I guess it's also a question, if separate repositories for the spec project and implementation are preferred, or one for everything (like jsonp)?

Not preferred. Required. Implementations must be separate from specifications. Specification projects that currently include an implementation are considered by the Jakarta EE Specification Committee to be in an invalid state.

The Jakarta EE Specification Committee is generally of the opinion that keeping implementations separate from specifications is a good practice that encourages (or at least does not discourage) the creation of multiple Compatible Implementations. Frankly, I would expect the Specification Committee to outright reject a project that attempt to merge the two.

As part of the project refactoring exercise that will follow the Jakarta EE 8 release, we'll see an effort to take the small handful of projects that do combine specifications and implementations in a single project/repository and rip them apart.

**Comment by keilw** [comment]
I spoke to a Jetty lead at JCrete also about potentially using or contributing to a Jakarta Config efort, because Jetty has some very "exotic" types of configuration based on files that are derived from Windows INI.
